# Generated by Django 4.2 on 2023-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='id',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
