# Generated by Django 4.2 on 2023-06-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month_finance_out',
            old_name='d',
            new_name='date',
        ),
    ]
