# Generated by Django 4.2 on 2023-04-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_out',
            name='bills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.bill'),
        ),
        migrations.AlterField(
            model_name='finance_out',
            name='invoice_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.invoice'),
        ),
        migrations.AlterField(
            model_name='finance_out',
            name='payment_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.payment'),
        ),
    ]
