# Generated by Django 4.2 on 2023-05-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_account',
            name='ifsc',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='firstname',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='lastname',
            field=models.CharField(max_length=15),
        ),
    ]
