# Generated by Django 4.2 on 2023-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_in',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
