# Generated by Django 4.2 on 2023-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_d_month_finance_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_in',
            name='ref_no',
            field=models.CharField(default=0, max_length=30, unique=True),
        ),
    ]
