# Generated by Django 4.2 on 2023-05-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_invoice_id_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
