# Generated by Django 4.2 on 2023-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_finance_in_amount'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='finance_in',
            index=models.Index(fields=['-id'], name='account_fin_id_9d56aa_idx'),
        ),
    ]
