# Generated by Django 4.2 on 2023-04-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_finance_out_bills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='received_transfer',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
