# Generated by Django 4.2 on 2023-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_add_account_ifsc_alter_usertable_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='firstname',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
