# Generated by Django 4.2 on 2023-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_invoice_received_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='received_transfer',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=20),
        ),
    ]
