# Generated by Django 4.2 on 2023-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_invoice_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='received_transfer',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance_in',
            name='ref_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='finance_out',
            name='ref_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_ref_no',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
