# Generated by Django 4.2 on 2023-05-22 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_usertable_email_alter_usertable_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_account',
            name='acc_no',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='add_account',
            name='ifsc',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[0-9]{6}$')]),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='mob',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^[0-9]', 'Enter a valid mobile number.')]),
        ),
    ]
