# Generated by Django 4.2 on 2023-04-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_payment_received_transfer_alter_finance_in_ref_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance_in',
            name='invoice_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.invoice'),
        ),
        migrations.AlterField(
            model_name='finance_in',
            name='payment_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.payment'),
        ),
    ]
