# Generated by Django 4.2 on 2023-05-22 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_usertable_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_account',
            name='acc_no',
            field=models.BigIntegerField(default=0, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{9,18}$')]),
        ),
        migrations.AlterField(
            model_name='add_account',
            name='current_bal',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.RegexValidator('^(?!0\\.00)\\d{1,3}(?:,?\\d{3})*(?:\\.\\d{2})?$')]),
        ),
        migrations.AlterField(
            model_name='add_account',
            name='current_due',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.RegexValidator('^(?!0\\.00)\\d{1,3}(?:,?\\d{3})*(?:\\.\\d{2})?$')]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.BigIntegerField(default=0, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$')]),
        ),
    ]
