# Generated by Django 4.2 on 2023-04-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_finance_in_invoice_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_in',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.add_account'),
        ),
        migrations.AddField(
            model_name='finance_out',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.add_account'),
        ),
    ]
