# Generated by Django 4.2 on 2023-04-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_finance_in_account_finance_out_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_account',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
