# Generated by Django 4.2 on 2023-04-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_add_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_account',
            name='acc_no',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
