# Generated by Django 4.2 on 2023-05-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_add_account_acc_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=30)),
                ('vendor_address', models.CharField(max_length=100)),
                ('vendor_mobileno', models.IntegerField()),
                ('vendor_GSTno', models.CharField(max_length=15)),
                ('vendor_PanCard', models.CharField(max_length=10)),
                ('vendor_TDS', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='finance_in',
            name='amount',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='finance_in',
            name='ref_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='finance_in',
            name='tds_tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='deduction',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='deduction_reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_ref_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='adhar_no',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='doj',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='fathername',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='firstname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='lastname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='mothername',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='pan_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='firstname',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='lastname',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='mob',
            field=models.BigIntegerField(max_length=13),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='finance_in',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.vendor'),
        ),
        migrations.AddField(
            model_name='finance_out',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.vendor'),
        ),
    ]
