# Generated by Django 4.2 on 2023-04-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_evaluation_notes_alter_evaluation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='graduation',
            field=models.CharField(choices=[('ug', 'UG'), ('pg', 'PG')], default='ug', max_length=20),
        ),
    ]
