# Generated by Django 4.2 on 2023-05-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_ref_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
