# Generated by Django 4.2 on 2023-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_invoice_invoice_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='choosefile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Month_Finance_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('salary_process', models.CharField(max_length=20)),
                ('final', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='finance_out',
            name='account',
        ),
        migrations.RemoveField(
            model_name='finance_out',
            name='bills',
        ),
        migrations.RemoveField(
            model_name='finance_out',
            name='final',
        ),
        migrations.RemoveField(
            model_name='finance_out',
            name='salary_process',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_ref_no',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='mob',
            field=models.BigIntegerField(null=True),
        ),
    ]
