# Generated by Django 4.2 on 2023-04-25 07:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_payroll_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 25, 7, 29, 16, 657506, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
