# Generated by Django 4.2 on 2023-06-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_choosefile_month_finance_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_ref_no',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
