# Generated by Django 4.2 on 2023-04-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_finance_out_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Add_bill',
            field=models.IntegerField(default=0),
        ),
    ]
