# Generated by Django 4.2 on 2023-04-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_bill_add_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='Add_bill',
            new_name='Added_bill',
        ),
        migrations.RemoveField(
            model_name='finance_out',
            name='result',
        ),
    ]
