# Generated by Django 4.2 on 2023-05-03 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_bill_add_bill_remove_finance_out_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='electricity_bill',
            new_name='bill_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='food_bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='other_bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='paper_bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='rent_bill',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='water_bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_no',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
