# Generated by Django 4.2 on 2023-04-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_bill_added_bill_bill_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='finance_out',
            name='final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
