# Generated by Django 4.2 on 2023-05-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_electricity_bill_bill_bill_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_amount',
            field=models.IntegerField(),
        ),
    ]
