# Generated by Django 4.2 on 2023-05-03 09:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_finance_out_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='dob',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 9, 31, 48, 43471, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='doj',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='provision_period',
            field=models.DateField(default=datetime.datetime(2023, 5, 3, 9, 32, 24, 198218, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
