# Generated by Django 4.2 on 2023-05-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_payroll_dob_payroll_doj_payroll_provision_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='provision_period',
            new_name='probation_period',
        ),
    ]
