# Generated by Django 4.2 on 2023-05-03 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_alter_bill_bill_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
