# Generated by Django 4.2 on 2023-05-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_rename_provision_period_payroll_probation_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='probation_days',
            field=models.IntegerField(default='90'),
        ),
    ]
