# Generated by Django 4.2 on 2023-05-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_payroll_probation_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='probation_period',
        ),
        migrations.AlterField(
            model_name='payroll',
            name='probation_days',
            field=models.IntegerField(default=90),
        ),
    ]
